### ISSUE TITLE
As an admin, I want to embed the handsfree.js sandbox into my site

### ISSUE THREAD

**Issue by labofoz** [BrowseHandsfree/handsfree.js#2]
There are many reasons why this would be awesome!
- [x] I can embed the sandbox as the "hero" unit of browsehandsfree.com
- ~~I can create a glitch.com project, and others can fork their own copy~~
- ~~I can live stream myself from any computer/device with no setup or post processing (might need to break this one into a separate story tho)~~

## Tasks
- [x] Build script
- [x] Create a new repo: browsehandsfree-discourse
- [x] Setup instructions for editing the repo and connect it as a theme-component on browsehandsfree.com
- [x] Embed the handsfree.js sandbox below the header and make it full screen
- [x] Make sure you can still click around in the forum handsfree

**Comment by labofoz** [comment]
Completed as part of #5 

![](https://media.giphy.com/media/JnvOYlWf4Pgr3COcOb/source.gif)
