### ISSUE TITLE
As a developer and user, I want handtracking

### ISSUE THREAD

**Issue by labofoz** [BrowseHandsfree/handsfree.js#3]
## Scope
- [ ] I can enable just handtracking
- [ ] I can configure the handtracker settings
- [ ] I have an easy API for common gestures

## Tasks
- [x] Require handtrack.js when `{models: {handtrack: {enabled: true}}}`
- [ ] Run inference with handtrack
