### ISSUE TITLE
As a developer, I want to add plugins

### ISSUE THREAD

**Issue by labofoz** [BrowseHandsfree/handsfree.js#4]
## Scope
- [ ] I can use `handsfree.use()` method to add a new plugin

## Tasks
- [ ] Add the `handsfree.use()` method to create a plugin
- [ ] It should call the "onFrame" on every inference frame
