### ISSUE TITLE
As a WordPress admin, I want to embed the Handsfree.js sandbox into my blog

### ISSUE THREAD

**Issue by labofoz** [BrowseHandsfree/handsfree.js#5]
I'd like to embed the sandbox inline with [our new blog](https://browsehandsfree.com) (without an iframe).

## Scope
- [x] Add an npm script: `npm run wordpress`
- [x] Commit to a `/wordpress` branch
- [x] Update all readmes

## Tasks
- [x] Create WordPress plugin manifest and files in `builders/wordpress/inc/`
- [x] Create a [shortcode](https://codex.wordpress.org/Shortcode_API)
- [x] Use queryselectors within the node build script to extract just the parts from `dist/index.html` that we need (to avoid complexity)
- [x] Inject those parts into `sandbox.html` and import that from the WordPress plugin
- [x] Rewrite URLs

**Comment by labofoz** [comment]
Hell yeah! It still needs sooooo much work but integration is now working: https://browsehandsfree.com/handsfree-js

![](https://media.giphy.com/media/JnvOYlWf4Pgr3COcOb/source.gif)
